#
# Module manifest for module 'PSLogs'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2023-08-30
#

@{
    RootModule           = 'PSLogs.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = 'b4b6813f-6ab8-4798-b42e-5dd6d3f0eee8'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'asd'
    NestedModules        = @()
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            LicenseUri               = 'https://github.com/hanpq/PSLogs/blob/master/LICENSE'
            #RequireLicenseAcceptance = $false
            Prerelease               = ''
            Tags                     = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri               = 'https://getps.dev/modules/PSLogs/getstarted'
            ReleaseNotes             = ''
        }
    }
}
