#
# Module manifest for module 'PSLogs'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2023-08-24
#

@{
    RootModule           = 'PSLogs.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '13599ad2-2234-44f2-933f-ffbb2e8e64c6'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Powershell Logging Module. Support multiple logging targets, including console, file, sqlite, winevent, gelf, slack etc.'
    NestedModules        = @()
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            LicenseUri               = 'https://github.com/hanpq/PSLogs/blob/master/LICENSE'
            RequireLicenseAcceptance = $false
            Prerelease               = ''
            Tags                     = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri               = 'https://getps.dev/modules/PSLogs/getstarted'
            ReleaseNotes             = ''
        }
    }
}
